#!/usr/bin/env bash
version="21.1.16"
name="xorg-server"
depends="xorg-util-macros,xorgproto,font-util"
description="X grafik sunucu"
source="https://www.x.org/releases/individual/xserver/xorg-server-${version}.tar.xz"
groups="x11.base"

# Paketin yükleneceği tasarlanan sistem konumu
DESTDIR="$HOME/distro/rootfs"
# Derleme konumu
ROOTBUILDDIR="/tmp/kly/build"
# Derleme yapılan paketin derleme konumun
BUILDDIR="/tmp/kly/build/build-${name}-${version}"
# paketin derleme talimatının verildiği konum
PACKAGEDIR=$(pwd)
# Paketin kaynak kodlarının olduğu konum
SOURCEDIR="/tmp/kly/build/${name}-${version}"
# initsetup
# derleme dizini yoksa oluşturuluyor
mkdir -p $ROOTBUILDDIR
# içeriği temizleniyor
rm -rf $ROOTBUILDDIR/*
cd $ROOTBUILDDIR #dizinine geçiyoruz
wget --no-check-certificate ${source}
# isimde boşluk varsa silme işlemi yapılıyor
for f in *\ *; do mv "$f" "${f// /}"; done
dowloadfile=$(ls|head -1)
filetype=$(file -b --extension $dowloadfile|cut -d'/' -f1)
if [ "${filetype}" == "???" ]; then unzip ${dowloadfile}; else tar -xvf ${dowloadfile};fi
director=$(find ./* -maxdepth 0 -type d)
directorname=$(basename ${director})
if [ "${directorname}" != "${name}-${version}" ]; then mv $directorname ${name}-${version};fi
mkdir -p $BUILDDIR && mkdir -p $DESTDIR && cd $SOURCEDIR
# setup
meson setup $BUILDDIR --prefix=/usr \
	--libdir=/usr/lib64/ \
	-Dipv6=true \
	-Dxvfb=true \
	-Dxnest=true \
	-Dxcsecurity=true \
	-Dxorg=true \
	-Dxephyr=true \
	-Dglamor=true \
	-Dlibunwind=true \
	-Dudev=true \
	-Ddtrace=false \
	-Dsystemd_logind=false \
	-Ddocs=false \
	-Dxselinux=false \
	-Dsuid_wrapper=true \
	-Dxkb_dir=/usr/share/X11/xkb \
	-Dxkb_output_dir=/var/lib/xkb
# build
ninja -C $BUILDDIR
# package
DESTDIR=$DESTDIR ninja -C $BUILDDIR install

