#!/usr/bin/env bash
version="3.1.1"
name="audit"
depends=""
description="Servis Yöneticisi"
source="https://github.com/linux-audit/audit-userspace/archive/refs/tags/v${version}.tar.gz"
groups="sys.process"

# Paketin yükleneceği tasarlanan sistem konumu
DESTDIR="$HOME/distro/rootfs"
# Derleme konumu
ROOTBUILDDIR="/tmp/kly/build"
# Derleme yapılan paketin derleme konumun
BUILDDIR="/tmp/kly/build/build-${name}-${version}"
# paketin derleme talimatının verildiği konum
PACKAGEDIR=$(pwd)
# Paketin kaynak kodlarının olduğu konum
SOURCEDIR="/tmp/kly/build/${name}-${version}"
# initsetup
# derleme dizini yoksa oluşturuluyor
mkdir -p $ROOTBUILDDIR
# içeriği temizleniyor
rm -rf $ROOTBUILDDIR/*
cd $ROOTBUILDDIR #dizinine geçiyoruz
wget --no-check-certificate ${source}
# isimde boşluk varsa silme işlemi yapılıyor
for f in *\ *; do mv "$f" "${f// /}"; done
dowloadfile=$(ls|head -1)
filetype=$(file -b --extension $dowloadfile|cut -d'/' -f1)
if [ "${filetype}" == "???" ]; then unzip ${dowloadfile}; else tar -xvf ${dowloadfile};fi
director=$(find ./* -maxdepth 0 -type d)
directorname=$(basename ${director})
if [ "${directorname}" != "${name}-${version}" ]; then mv $directorname ${name}-${version};fi
mkdir -p $BUILDDIR && mkdir -p $DESTDIR && cd $SOURCEDIR
# setup
cp $PACKAGEDIR/audit/auditd.initd /tmp/kly/build/auditd.initd
cp $PACKAGEDIR/audit/auditd.confd /tmp/kly/build/auditd.confd

autoreconf -fvi
./configure --prefix=/usr \
	--libdir=/usr/lib64/ \
	--sysconfdir=/etc \
        --disable-zos-remote \
        --disable-listener \
        --disable-systemd \
        --disable-gssapi-krb5 \
        --enable-shared=audit \
	--with-arm \
	--with-aarch64\
	--without-python \
	--without-python3 \
	--with-libcap-ng=no 
# build
make
# package
make install DESTDIR=$DESTDIR
install -Dm755 ../auditd.initd "$DESTDIR"/etc/init.d/auditd
install -Dm755 ../auditd.confd "$DESTDIR"/etc/conf.d/auditd

