#!/usr/bin/env bash
name="thunar-volman"
version="4.18.0"
description="Automatic management of removable drives and media for Thunar"
source="https://archive.xfce.org/src/xfce/thunar-volman/${version%.*}/thunar-volman-${version}.tar.bz2"
depends="hicolor-icon-theme,libxfce4ui,thunar"
builddepend="intltool"
group="xfce.base"

setup(){
    cd $SOURCEDIR
    ./configure --prefix=/usr \
        --libdir=/usr/lib64 \
		--sysconfdir=/etc \
		--localstatedir=/var \
		--disable-debug
}
build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}
