#!/usr/bin/env bash
name="gtk-layer-shell"
version="0.9.0"
description="Library to create Wayland desktop components using the Layer Shell protocol"
source="https://github.com/wmww/gtk-layer-shell/archive/refs/tags/v${version}.tar.gz"
depends="gtk3,wayland"
builddepend="meson,gtk-doc,gobject-introspection"
group="gui.libs"

setup(){
    cd $SOURCEDIR
    meson setup $BUILDDIR \
        --prefix=/usr \
        --libdir=/usr/lib64 \
		--wrap-mode=nofallback \
		--buildtype=plain \
		-Dtests=true \
		-Ddocs=true \
		-Dintrospection=true
}
build(){
    meson compile -C $BUILDDIR
}

package(){
    DESTDIR="$DESTDIR" meson install -C $BUILDDIR
}
