#!/usr/bin/env bash
version="1.4.3"
name="xinit"
depends="libx11"
description="X Pencere Sistemi başlangıç yazılımı"
source="https://xorg.freedesktop.org/releases/individual/app/xinit-${version}.tar.gz"
groups="x11.apps"

# Paketin yükleneceği tasarlanan sistem konumu
DESTDIR="$HOME/distro/rootfs"
# Derleme konumu
ROOTBUILDDIR="/tmp/kly/build"
# Derleme yapılan paketin derleme konumun
BUILDDIR="/tmp/kly/build/build-${name}-${version}"
# paketin derleme talimatının verildiği konum
PACKAGEDIR=$(pwd)
# Paketin kaynak kodlarının olduğu konum
SOURCEDIR="/tmp/kly/build/${name}-${version}"
# initsetup
# derleme dizini yoksa oluşturuluyor
mkdir -p $ROOTBUILDDIR
# içeriği temizleniyor
rm -rf $ROOTBUILDDIR/*
cd $ROOTBUILDDIR #dizinine geçiyoruz
wget --no-check-certificate ${source}
# isimde boşluk varsa silme işlemi yapılıyor
for f in *\ *; do mv "$f" "${f// /}"; done
dowloadfile=$(ls|head -1)
filetype=$(file -b --extension $dowloadfile|cut -d'/' -f1)
if [ "${filetype}" == "???" ]; then unzip ${dowloadfile}; else tar -xvf ${dowloadfile};fi
director=$(find ./* -maxdepth 0 -type d)
directorname=$(basename ${director})
if [ "${directorname}" != "${name}-${version}" ]; then mv $directorname ${name}-${version};fi
mkdir -p $BUILDDIR && mkdir -p $DESTDIR && cd $SOURCEDIR
# setup

cp -prfv $PACKAGEDIR/${name}/files /tmp/kly/build/files/

autoreconf -fvi
./configure --prefix=/usr --libdir=/usr/lib64/ -sysconfdir=/etc
# build
make
# package
make install DESTDIR=$DESTDIR
install -m755 -D ../files/Xwrapper.config "$DESTDIR"/etc/X11/Xwrapper.config
install -m755 -D ../files/xinitrc "$DESTDIR"/etc/X11/xinit/xinitrc
install -m755 -D ../files/Xsession "$DESTDIR"/etc/X11/xinit/Xsession
install -m755 ../files/xserverrc "$DESTDIR"/etc/X11/xinit/xserverrc
install -m755 -D ../files/xinit.sysconf "$DESTDIR"/etc/sysconf.d/xinit
install -m755 -D ../files/xinit.initd "$DESTDIR"/etc/init.d/xinit
install -m755 -D ../files/xinit.confd "$DESTDIR"/etc/conf.d/xinit
install ../files/Xresources "$DESTDIR"/etc/X11/Xresources
# allow local connections config
mkdir -p "$DESTDIR"/etc/X11/xinit/xinitrc.d
echo "#!/bin/sh" > "$DESTDIR"/etc/X11/xinit/xinitrc.d/10-local.sh
echo "xhost +local:" >> "$DESTDIR"/etc/X11/xinit/xinitrc.d/10-local.sh
chmod 754 "$DESTDIR"/etc/X11/xinit/xinitrc.d/10-local.sh

