#!/usr/bin/env bash
version="1.16.2"
name="dbus"
description="Freedesktop.org mesaj sistemi"
source="https://dbus.freedesktop.org/releases/dbus/dbus-${version}.tar.xz"
depends="audit,expat,libcap-ng,elogind,libX11,libunwind"
group="sys.apps"

# Paketin yükleneceği tasarlanan sistem konumu
DESTDIR="$HOME/distro/rootfs"
# Derleme konumu
ROOTBUILDDIR="/tmp/kly/build"
# Derleme yapılan paketin derleme konumun
BUILDDIR="/tmp/kly/build/build-${name}-${version}"
# paketin derleme talimatının verildiği konum
PACKAGEDIR=$(pwd)
# Paketin kaynak kodlarının olduğu konum
SOURCEDIR="/tmp/kly/build/${name}-${version}"
# initsetup
# derleme dizini yoksa oluşturuluyor
mkdir -p $ROOTBUILDDIR
# içeriği temizleniyor
rm -rf $ROOTBUILDDIR/*
cd $ROOTBUILDDIR #dizinine geçiyoruz
wget --no-check-certificate ${source}
# isimde boşluk varsa silme işlemi yapılıyor
for f in *\ *; do mv "$f" "${f// /}"; done
dowloadfile=$(ls|head -1)
filetype=$(file -b --extension $dowloadfile|cut -d'/' -f1)
if [ "${filetype}" == "???" ]; then unzip ${dowloadfile}; else tar -xvf ${dowloadfile};fi
director=$(find ./* -maxdepth 0 -type d)
directorname=$(basename ${director})
if [ "${directorname}" != "${name}-${version}" ]; then mv $directorname ${name}-${version};fi
mkdir -p $BUILDDIR && mkdir -p $DESTDIR && cd $SOURCEDIR
# setup
cp -r $PACKAGEDIR/dbus/files/ /tmp/kly/build/

meson setup $BUILDDIR --prefix=/usr --libdir=/usr/lib64/\
	-Dsystemd=disabled \
	-Duser_session=false \
	-Dapparmor=disabled \
	-Ddbus_user=dbus \
	-Dkqueue=disabled \
	-Dlaunchd=disabled \
	-Drelocation=disabled \
	-Dselinux=disabled \
	-Dx11_autolaunch=enabled
# build
ninja -C $BUILDDIR
# package
DESTDIR=$DESTDIR ninja install -C $BUILDDIR 

mkdir -p "$DESTDIR"/etc/init.d "$DESTDIR"/etc/local.d "$DESTDIR"/etc/X11/xinit/xinitrc.d/
install ../files/dbus.initd "$DESTDIR"/etc/init.d/dbus
install ../files/dbus.xinit "$DESTDIR"/etc/X11/xinit/xinitrc.d/30-dbus-launch.sh
install ../files/xrunsystemd.init.d ${DESTDIR}/etc/init.d/xrunsystemd
install ../files/runsystemd.local.d ${DESTDIR}/etc/local.d/runsystemd

for level in boot default nonetwork shutdown sysinit ; do
	mkdir -p ${DESTDIR}/etc/runlevels/$level
done
cd ${DESTDIR}/etc/runlevels/default
ln -s ../../init.d/xrunsystemd xrunsystemd
ln -s ../../init.d/dbus dbus

