#!/usr/bin/env bash
name="xfce4-settings"
version="4.19.2"
description="Xfce's Configuration System"
source="https://archive.xfce.org/src/xfce/xfce4-settings/${version%.*}/xfce4-settings-${version}.tar.bz2"
depends="exo,garcon,hicolor-icon-theme,libnotify,gnome-themes-standard,libxklavier"
builddepend="intltool"
group="xfce.base"

setup(){
    cd $SOURCEDIR
    ./configure --prefix=/usr \
        --libdir=/usr/lib64 \
		--sysconfdir=/etc \
		--sbindir=/usr/bin \
		--localstatedir=/var \
		--enable-xrandr \
		--enable-xcursor \
		--enable-libnotify \
		--enable-libxklavier \
		--enable-pluggable-dialogs \
		--enable-sound-settings \
		--disable-debug



}
build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}
