#!/usr/bin/env bash
name="xfdesktop"
version="4.19.3"
description="Xfce's desktop manager"
source="https://archive.xfce.org/src/xfce/xfdesktop/${version%.*}/xfdesktop-${version}.tar.bz2"
depends="exo,garcon,libwnck3,libxfce4ui,thunar"
builddepend="intltool,xfce4-dev-tools"
group="xfce.base"

setup(){
    cd $SOURCEDIR
    ./configure --prefix=/usr \
        --libdir=/usr/lib64 \
		--sysconfdir=/etc \
        --enable-thunarx \
		--enable-notifications \
		--disable-debug 

}
build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}
