#!/usr/bin/env bash
version="1.27.1-1"
name="libinput"
depends="eudev,mtdev,libevdev"
description="Giriş cihazı yönetimi ve etkinlik işleme kütüphanesi"
source="https://salsa.debian.org/cb/libinput/-/archive/debian/${version}/libinput-debian-${version}.tar.gz"
groups="dev.libs"

# Paketin yükleneceği tasarlanan sistem konumu
DESTDIR="$HOME/distro/rootfs"
# Derleme konumu
ROOTBUILDDIR="/tmp/kly/build"
# Derleme yapılan paketin derleme konumun
BUILDDIR="/tmp/kly/build/build-${name}-${version}"
# paketin derleme talimatının verildiği konum
PACKAGEDIR=$(pwd)
# Paketin kaynak kodlarının olduğu konum
SOURCEDIR="/tmp/kly/build/${name}-${version}"
# initsetup
# derleme dizini yoksa oluşturuluyor
mkdir -p $ROOTBUILDDIR
# içeriği temizleniyor
rm -rf $ROOTBUILDDIR/*
cd $ROOTBUILDDIR #dizinine geçiyoruz
wget --no-check-certificate ${source}
# isimde boşluk varsa silme işlemi yapılıyor
for f in *\ *; do mv "$f" "${f// /}"; done
dowloadfile=$(ls|head -1)
filetype=$(file -b --extension $dowloadfile|cut -d'/' -f1)
if [ "${filetype}" == "???" ]; then unzip ${dowloadfile}; else tar -xvf ${dowloadfile};fi
director=$(find ./* -maxdepth 0 -type d)
directorname=$(basename ${director})
if [ "${directorname}" != "${name}-${version}" ]; then mv $directorname ${name}-${version};fi
mkdir -p $BUILDDIR && mkdir -p $DESTDIR && cd $SOURCEDIR
# setup
meson setup $BUILDDIR --prefix=/usr \
	--libdir=/usr/lib64/ \
	-Dudev-dir=/lib64/udev \
	-Dlibwacom=true  \
	-Ddebug-gui=false \
	-Dtests=false
# build
ninja -C $BUILDDIR
# package
DESTDIR=$DESTDIR ninja -C $BUILDDIR install

