#!/usr/bin/env bash
name="xfwm4"
version="4.18.0"
description="Xfce's window manager"
source="https://archive.xfce.org/src/xfce/xfwm4/${version%.*}/xfwm4-${version}.tar.bz2"
depends="libepoxy,libwnck3,libxfce4ui,xfconf"
builddepend="intltool"
group="xfce.base"

setup(){
    cd $SOURCEDIR
    ./configure --prefix=/usr \
        --libdir=/usr/lib64 \
		--sysconfdir=/etc \
		--localstatedir=/var \
		--enable-startup-notification \
		--enable-randr \
		--enable-compositor \
		--enable-xsync \
		--disable-debug


}
build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}
