#!/usr/bin/env bash
name="xfce4-power-manager"
version="4.19.3"
description="Power Manager for Xfce"
source="https://archive.xfce.org/src/xfce/xfce4-power-manager/${version%.*}/xfce4-power-manager-${version}.tar.bz2"
depends="libnotify,libxfce4ui,upower"
builddepend="intltool"
group="xfce.base"

setup(){
    cd $SOURCEDIR
    ./configure --prefix=/usr \
        --libdir=/usr/lib64 \
		--sysconfdir=/etc \
		--sbindir=/usr/bin \
		--localstatedir=/var \
		--disable-network-manager \
		--enable-polkit \
		--disable-debug

}
build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}
