#!/usr/bin/env bash
name="tumbler"
version="4.19.1"
description="Thumbnail service implementing the thumbnail management D-Bus specification"
source="https://archive.xfce.org/src/xfce/tumbler/${version%.*}/tumbler-${version}.tar.bz2"
depends="glib,gdk-pixbuf,libxfce4util"
builddepend="intltool"
group="xfce.base"

setup(){
    cd $SOURCEDIR
    ./configure --prefix=/usr \
        --libdir=/usr/lib64 \
		--sysconfdir=/etc \
		--disable-debug

}
build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
    rm -rf $DESTDIR/usr/lib
}
