#!/usr/bin/env bash
name="xfce4-appfinder"
version="4.19.2"
description="Application launcher and finder"
source="https://archive.xfce.org/src/xfce/xfce4-appfinder/${version%.*}/xfce4-appfinder-${version}.tar.bz2"
depends="garcon,libxfce4ui,xfconf"
builddepend="intltool"
group="xfce.base"

setup(){
    cd $SOURCEDIR
    ./configure --prefix=/usr \
        --libdir=/usr/lib64 \
		--sysconfdir=/etc \
		--localstatedir=/var \
		--disable-debug

}
build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}
