#!/usr/bin/env bash
version="0.44.2"
name="pixman"
depends=""
description="Düşük seviyeli piksel manipülasyon rutinleri"
source="https://www.x.org/archive/individual/lib/pixman-${version}.tar.gz"
groups="x11.libs"

# Paketin yükleneceği tasarlanan sistem konumu
DESTDIR="$HOME/distro/rootfs"
# Derleme konumu
ROOTBUILDDIR="/tmp/kly/build"
# Derleme yapılan paketin derleme konumun
BUILDDIR="/tmp/kly/build/build-${name}-${version}"
# paketin derleme talimatının verildiği konum
PACKAGEDIR=$(pwd)
# Paketin kaynak kodlarının olduğu konum
SOURCEDIR="/tmp/kly/build/${name}-${version}"
# initsetup
# derleme dizini yoksa oluşturuluyor
mkdir -p $ROOTBUILDDIR
# içeriği temizleniyor
rm -rf $ROOTBUILDDIR/*
cd $ROOTBUILDDIR #dizinine geçiyoruz
wget --no-check-certificate ${source}
# isimde boşluk varsa silme işlemi yapılıyor
for f in *\ *; do mv "$f" "${f// /}"; done
dowloadfile=$(ls|head -1)
filetype=$(file -b --extension $dowloadfile|cut -d'/' -f1)
if [ "${filetype}" == "???" ]; then unzip ${dowloadfile}; else tar -xvf ${dowloadfile};fi
director=$(find ./* -maxdepth 0 -type d)
directorname=$(basename ${director})
if [ "${directorname}" != "${name}-${version}" ]; then mv $directorname ${name}-${version};fi
mkdir -p $BUILDDIR && mkdir -p $DESTDIR && cd $SOURCEDIR
# setup
meson setup $BUILDDIR --prefix=/usr --libdir=/usr/lib64/\
	-D loongson-mmi=disabled \
	-D vmx=disabled \
	-D arm-simd=disabled \
	-D neon=disabled \
	-D a64-neon=disabled \
	-D rvv=disabled \
	-D mips-dspr2=disabled \
	-D gtk=disabled
# build
ninja -C $BUILDDIR
# package
DESTDIR=$DESTDIR ninja install -C $BUILDDIR 

