#!/usr/bin/env bash
version="25.0.1"
name="mesa"
depends="clang,expat,libdrm,libelf,libclc,bison,flex"
description="Açık kaynak OpenGL sürücüleri"
source="https://gitlab.freedesktop.org/mesa/mesa/-/archive/mesa-${version}/mesa-mesa-${version}.tar.gz"
groups="x11.base"

# Paketin yükleneceği tasarlanan sistem konumu
DESTDIR="$HOME/distro/rootfs"
# Derleme konumu
ROOTBUILDDIR="/tmp/kly/build"
# Derleme yapılan paketin derleme konumun
BUILDDIR="/tmp/kly/build/build-${name}-${version}"
# paketin derleme talimatının verildiği konum
PACKAGEDIR=$(pwd)
# Paketin kaynak kodlarının olduğu konum
SOURCEDIR="/tmp/kly/build/${name}-${version}"
# initsetup
# derleme dizini yoksa oluşturuluyor
mkdir -p $ROOTBUILDDIR
# içeriği temizleniyor
rm -rf $ROOTBUILDDIR/*
cd $ROOTBUILDDIR #dizinine geçiyoruz
wget --no-check-certificate ${source}
# isimde boşluk varsa silme işlemi yapılıyor
for f in *\ *; do mv "$f" "${f// /}"; done
dowloadfile=$(ls|head -1)
filetype=$(file -b --extension $dowloadfile|cut -d'/' -f1)
if [ "${filetype}" == "???" ]; then unzip ${dowloadfile}; else tar -xvf ${dowloadfile};fi
director=$(find ./* -maxdepth 0 -type d)
directorname=$(basename ${director})
if [ "${directorname}" != "${name}-${version}" ]; then mv $directorname ${name}-${version};fi
mkdir -p $BUILDDIR && mkdir -p $DESTDIR && cd $SOURCEDIR
# setup
meson setup $BUILDDIR --prefix=/usr \
	-Db_ndebug=true \
	-Db_lto=true \
	-Dplatforms=x11,wayland \
	-Dgallium-drivers=r300,r600,radeonsi,nouveau,virgl,svga,swrast,i915,iris,crocus,zink,d3d12 \
	-Dvulkan-drivers=amd,intel,intel_hasvk,swrast \
	-Dvulkan-layers=device-select,intel-nullhw,overlay \
	-Degl=enabled \
	-Dgallium-extra-hud=true \
	-Dgallium-nine=true \
	-Dgallium-va=enabled \
	-Dgallium-vdpau=enabled \
	-Dgallium-xa=enabled \
	-Dgallium-opencl=icd \
	-Dgbm=enabled \
	-Dgles1=disabled \
	-Dgles2=enabled \
	-Dglvnd=enabled \
	-Dglx=dri \
	-Dllvm=enabled \
	-Dosmesa=true \
	-Dshared-glapi=enabled \
	-Dvideo-codecs=vc1dec,h264dec,h264enc,h265dec,h265enc \
	-Dvalgrind=disabled \
	-Dlmsensors=disabled \
	-Dzstd=disabled \
	-Dmicrosoft-clc=disabled
# build
ninja -C $BUILDDIR
# package
DESTDIR=$DESTDIR ninja -C $BUILDDIR install

