#!/usr/bin/env bash
name="xfce4-whiskermenu-plugin"
version="2.8.3"
description="Menu for Xfce4"
source="https://github.com/gottcode/xfce4-whiskermenu-plugin/archive/refs/tags/v${version}.tar.gz"
depends="garcon,xfce4-panel,accountsservice"
builddepend="cmake"
group="xfce.base"

setup(){
	cd $SOURCEDIR
    cmake -B $BUILDDIR -G Ninja \
		-DCMAKE_BUILD_TYPE=Release \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=/usr/lib64 \
		-Wno-dev
}

build(){
    cmake --build $BUILDDIR
}

package(){
   DESTDIR=$DESTDIR cmake --install $BUILDDIR
}
